package com.example.myapplication;

public class Classes {
    public static String[] PLANT_CLASSES = new String[]{
            "Abelia",
            "Acanthus",
            "African Violet",
            "Agapanthus",
            "Agave",
            "Allium",
            "Alocasia",
            "Aloe",
            "Anemone",
            "Annual Leucanthemum",
            "Anthurium",
            "Aucuba",
            "Auriculas",
            "Border Buttercups",
            "Bromeliad",
            "Brugmansia",
            "Calamagrostis",
            "Calendula",
            "Camellia",
            "Ceanothus",
            "Conservatory Passion",
            "Daffodil",
            "Echeveria",
            "Echinacea",
            "Ferocactus",
            "Foxglove",
            "Garrya",
            "Gerbera",
            "Gunnera",
            "Hoya",
            "Hypoestes",
            "Knifophia",
            "Lavatera",
            "Miscanthus",
            "Monarda",
            "Nerine",
            "Nigella",
            "Phlox",
            "Poinsettia",
            "Pyracantha",
            "Rose",
            "Sansevieria",
            "Scabious",
            "Sea Holly",
            "Sempervivum",
            "Spider",
            "Strelitzia",
            "String of Beads",
            "Tree Peonies",
            "Tulip",
            "Venus Fly Trap",
            "Veronica",
            "Yew",
    };
}